output_path = "./output"

[properties]
name = "Tydi_Example"
top_level_implementation = "TydiDemoTop"
top_level_implementation_package = "example"
sugaring = ["student_schema_parser:top_impl"]

[files]
tydi_src = ["./std.td", "./example.td", "./output/student_schema_parser/src/student_schema_parser.td", "./snappy.td"]
